[directory]
truncation_length = 8
truncate_to_repo = false

[git_branch]
style = "bold green"

[custom.watson]
command = "watson status -p"  # shows output of command
when = """ [ "$(watson status -p)" != "No project started." ] """
prefix = ""
suffix = ""
symbol = "⌛"
disabled = true
